version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "20:53"
      timezone: "Asia/India"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "pip"
    labels:
      - "pip dependencies"
